#!/usr/bin/env node
// pass.mjs — the three file-editing jobs of pass.sh (5.0.0 · #45; moved to node at 7.6.0):
//
//   pass.mjs trace <UC file> <trace file> <ID> <date>   ⑭ move the evidence trail into UC-###.trace.md, leaving ONE counting line
//   pass.mjs deprecate <UC file> <date> <reason> <replaced by|->   add the History line "deprecated — …"
//   pass.mjs change <proposal.md> <date>                Status → applying, History +1 line
//
// The rule of `trace` (5.0.0): a step that is a tool for THINKING leaves a DECISION behind, not a document.
// Adversarial · Re-read · History are scratch paper: when the UC closes, the body moves to the file next door (git keeps it,
// a dispute reopens it) and one machine-countable line stays in place. Measured at runxops: of the 56 KB of UC-009.md, those three sections were 28.6 KB.
import fs from 'node:fs';
import { kw, kwW } from './kw.mjs';

const [, , cmd, ...a] = process.argv;
const esc = (x) => x.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const read = (p) => fs.readFileSync(p, 'utf8');

/** The body of the `## <name>` section up to the next `## ` (or the end of the file). Returns {start, end, body} or null.
 *  7.7.0: `name` is an ALTERNATION BODY (`Đọc lại|Re-read`) and not a fixed string — the section is found
 *  whichever language it is written in. A section name has no regex metacharacter, so no escaping is needed. */
function section(s, name) {
  const re = new RegExp('^## (?:' + name + ')[ \\t]*\\n', 'm');
  const m = re.exec(s);
  if (!m) return null;
  const start = m.index + m[0].length;
  const rest = s.slice(start);
  const nx = /^## /m.exec(rest);
  const end = nx ? start + nx.index : s.length;
  return { start, end, body: s.slice(start, end) };
}

if (cmd === 'trace') {
  const [f, tr, ID, today] = a;
  let s = read(f);
  const moved = [];

  // 7.7.0: `alt` is the alternation body used to FIND the section (found in either language), `head` is the section name
  // WRITTEN into the trace file per doc_lang. Before 7.7.0 these two were one string.
  const replace = (alt, head, summary) => {
    const sec = section(s, alt);
    if (!sec) return;
    const body = sec.body;
    if (body.includes('→ ' + ID + '.trace.md')) return;      // already compressed
    if (!body.trim()) return;                                 // empty — nothing to move
    // 7.4 (P-40): `<hash>`, `<label for="np-go">` and text in code ticks are CONTENT, not a template — drop them
    // before asking "is there a template left". A real template: YYYY-MM-DD · Run date: ___ · a remaining <...>.
    let t = body.replace(/`[^`\n]*`/g, '');
    t = t.replace(/<\/?[A-Za-z][A-Za-z0-9-]*(\s+[A-Za-z_:-]+(=("[^"]*"|'[^']*'|[^\s>]+))?)*\s*\/?>/g, '');
    if (new RegExp('YYYY-MM-DD|(?:' + kw('rundate') + '):\\s*_|<[^>\\n]+>').test(t)) return;
    moved.push([head, body.replace(/\n+$/, '') + '\n']);
    s = s.slice(0, sec.start) + summary + '\n\n' + s.slice(sec.end);
  };
  const RUN = kwW('rundate');
  const dateIn = (body) =>
    (new RegExp('(?:' + kw('rundate') + '):\\s*(\\d{4}-\\d{2}-\\d{2})').exec(body) ?? [, today])[1];

  let sec = section(s, kw('adversarial'));
  if (sec && new RegExp(kw('rundate')).test(sec.body)) {
    const n = (sec.body.match(/^\s*-\s*Q\d+\b/gm) ?? []).length;
    replace(kw('adversarial'), kwW('adversarial'),
      `- ${RUN}: ${dateIn(sec.body)} · 3 ${kwW('roles')} · ${n} ${kwW('questions')}, ${kwW('allapplied')} → ${ID}.trace.md`);
  }
  sec = section(s, kw('reread'));
  if (sec && /^- F\d+ /m.test(sec.body)) {
    const n = (sec.body.match(/^- F\d+ /gm) ?? []).length;
    const k = (sec.body.match(new RegExp('^- F\\d+ .*(?:' + kw('falsepos') + ')', 'gm')) ?? []).length;
    replace(kw('reread'), kwW('reread'),
      `- ${RUN}: ${dateIn(sec.body)} · ${n} ${kwW('findings')} · ${k} ${kwW('falsepos2')} · ${kwW('allapplied')} → ${ID}.trace.md`);
  }
  sec = section(s, 'History');
  if (sec && /^- v\d+ /m.test(sec.body)) {
    const vs = [...sec.body.matchAll(/^- v(\d+) /gm)].map((m) => Number(m[1]));
    replace('History', 'History',
      `- v${Math.max(...vs) + 1} (${today}): implemented · ${kwW('fullhistory')} → ${ID}.trace.md`);
  }
  sec = section(s, 'Open Questions');
  if (sec) {
    const closed = sec.body.match(/^[ \t]*[-*] \[x\].*\n?/gim) ?? [];
    if (closed.length) {
      moved.push([`Open Questions (${kwW('closedq')})`, closed.join('')]);
      const nb = sec.body.replace(/^[ \t]*[-*] \[x\].*\n?/gim, '');
      s = s.slice(0, sec.start) + nb + s.slice(sec.end);
    }
  }

  if (moved.length) {
    let old = '', head = '';
    try {
      old = read(tr);
    } catch {
      head = `# ${ID} — evidence trail\n\n`
        + `<!-- Generated by pass.sh close on ${today}. This is the SCRATCH PAPER of ${ID}: adversarial, the re-read,\n`
        + `     history, the closed questions. Not a file for ordinary reading — open it when you need to trace why a\n`
        + `     line in ${ID}.md came out the way it did. context.sh and decisions.sh do not read this file. -->\n`;
    }
    let out = old + head;
    for (const [h, b] of moved) out += `\n## ${h} — ${today}\n${b}`;
    fs.writeFileSync(tr, out);
    fs.writeFileSync(f, s);
    process.stdout.write(`  moved ${moved.length} sections into ${ID}.trace.md\n`);
  }

  // 8.0.0: on the new layout there is nothing to move — the trail was written to ${ID}.trace.md all along, and
  // everything above is the fallback that still serves a repo written before 8.0.0. What the close step still owes
  // is the closing line of the history, so append it to the trail's own `## History`.
  // Idempotent by content, not by date: a `): implemented` line already there means this ran, and running close
  // twice must not grow the file. `migrate --trace` relies on the same property.
  if (!section(s, 'History') && fs.existsSync(tr)) {
    let t = read(tr);
    const h = section(t, 'History');
    if (h && !/\): implemented\b/.test(h.body)) {
      const vs = [...h.body.matchAll(/^- v(\d+) /gm)].map((m) => Number(m[1]));
      const v = vs.length ? Math.max(...vs) + 1 : 1;
      const line = `- v${v} (${today}): implemented\n`;
      t = t.slice(0, h.end).replace(/\n*$/, '\n') + line + t.slice(h.end);
      fs.writeFileSync(tr, t);
      process.stdout.write(`  wrote v${v} implemented into ${ID}.trace.md\n`);
    }
  }
} else if (cmd === 'deprecate') {
  const [f, today, reason, by] = a;
  let s = read(f);
  const vs = [...s.matchAll(/^- v(\d+) /gm)].map((m) => Number(m[1]));
  const line = `- v${(vs.length ? Math.max(...vs) : 0) + 1} (${today}, ${kwW('byowner')}): deprecated — ${reason}`
    + (by !== '-' ? ` · ${kwW('replacedby')} ${by}` : ` · ${kwW('noreplacement')}`);
  const sec = section(s, 'History');
  if (sec) {
    const body = sec.body.replace(/\n+$/, '');
    s = s.slice(0, sec.start) + body + '\n' + line + '\n' + (sec.end < s.length ? '\n' : '') + s.slice(sec.end);
  } else {
    s = s.replace(/\n+$/, '') + '\n\n## History\n' + line + '\n';
  }
  fs.writeFileSync(f, s);
} else if (cmd === 'change') {
  const [p, d] = a;
  let s = read(p);
  s = s.replace(/^(## Status\n+)[a-z]+[ \t]*$/m, '$1applying');
  if (s.includes('## History') && !s.includes(`${d}: designed -> applying`)) {
    s = s.replace(/\n+$/, '') + `\n- ${d}: designed -> applying (${kwW('c_p5')})\n`;
  }
  fs.writeFileSync(p, s);
} else {
  process.stderr.write('usage: pass.mjs <trace|deprecate|change> …\n');
  process.exit(2);
}
